### ISSUE TITLE
Can't seem to have access to network components (list, create, etc).

### ISSUE THREAD

**Issue by martypare** [StackStorm/openstack#27]
Its most likely something stupid that I am missing but I keep getting the following error when trying to list networks, The rest of the setup appears to be ok since I can list servers as an example. Any help is appreciated.  

st2 run openstack.network.list
.
id: 5893f3af49f1e60985f14809
status: failed
parameters: None
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 242, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 154, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/openstack/actions/src/lib/base.py", line 25, in run
    self.parser = self._get_parser(kwargs.pop('ep'))
  File "/opt/stackstorm/packs/openstack/actions/src/lib/base.py", line 75, in _get_parser
    return command.get_parser('autogen')
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/openstackclient/network/common.py", line 146, in get_parser
    if self.app.client_manager.is_network_endpoint_enabled():
AttributeError: 'NoneType' object has no attribute 'client_manager'
"
  stdout: ''

**Comment by martypare** [comment]
Oups wrong project this was intended to be posted in Stackstorm-Openstack
